"""empty message

Revision ID: f396a9263093
Revises: 
Create Date: 2021-11-16 20:36:59.897445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f396a9263093'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.Column('gender', sa.String(length=254), nullable=False),
    sa.Column('text', sa.String(length=254), nullable=False),
    sa.Column('category', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('text')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=254), nullable=False),
    sa.Column('brands', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.Column('site', sa.String(length=254), nullable=False),
    sa.Column('price', sa.String(length=254), nullable=False),
    sa.Column('category', sa.String(length=254), nullable=False),
    sa.Column('blogposts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blogposts_id'], ['blogpost.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brands'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('price'),
    sa.UniqueConstraint('site')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('blogpost')
    # ### end Alembic commands ###
